# Generated by Django 2.1 on 2018-11-05 08:28

from django.db import migrations, models
import django.db.models.deletion
import workout_info.myField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', workout_info.myField.PartOfTheWorkout(blank=True, choices=[('0', '스트레칭'), ('1', '삼두근'), ('10', '유산소'), ('2', '이두근'), ('3', '어깨'), ('4', '가슴'), ('5', '등'), ('6', '복근'), ('7', '허벅지'), ('8', '종아리'), ('9', '엉덩이')], max_length=1, null=True)),
                ('eng_name', workout_info.myField.EngNameOfTheWorkout(blank=True, choices=[('0', 'Streching'), ('1', 'Triceps'), ('10', 'Cardio'), ('2', 'Biceps'), ('3', 'Shoulders'), ('4', 'Chest'), ('5', 'Back'), ('6', 'Core'), ('7', 'Thigh'), ('8', 'Calf'), ('9', 'Hip')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(blank=True, max_length=32, null=True)),
                ('kor_name', models.CharField(blank=True, max_length=32, null=True)),
                ('how', models.TextField(blank=True, max_length=1000, null=True)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout_info.Part')),
            ],
        ),
    ]
