# Generated by Django 2.1 on 2018-10-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aim',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='frequency',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
