# Generated by Django 2.1 on 2018-10-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
        ('accounts', '0014_auto_20181021_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='craft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='craft.Craft'),
        ),
    ]
