# Generated by Django 2.1 on 2018-10-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='craft',
        ),
    ]
