# Generated by Django 2.1 on 2018-10-24 12:08

from django.db import migrations, models
import django.db.models.deletion
import workout.myField


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='set',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='times',
            field=models.IntegerField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.WorkoutInfo'),
        ),
        migrations.AddField(
            model_name='week',
            name='week',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='workoutinfo',
            name='how',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutinfo',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=workout.myField.DayOfTheWeekField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1, null=True),
        ),
    ]
