# Generated by Django 2.1 on 2018-10-25 07:53

from django.db import migrations, models
import django.db.models.deletion
import workout.myField


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20181024_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['day']},
        ),
        migrations.RemoveField(
            model_name='day',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='week',
            name='day',
        ),
        migrations.RemoveField(
            model_name='week',
            name='week',
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.Week'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.Day'),
        ),
        migrations.AddField(
            model_name='week',
            name='monday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='number',
            field=workout.myField.NumberOfTheWeekField(blank=True, choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Fourth')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
