# Generated by Django 2.1 on 2018-10-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20181027_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.FileField(blank=True, null=True, upload_to='')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.Day')),
            ],
        ),
    ]
