# Generated by Django 2.1 on 2018-10-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_workoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
