# Generated by Django 2.1 on 2018-10-27 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0007_day_done'),
    ]


    operations = [
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='week',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.Plan'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='times',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
